const yargs = require('yargs');

let now = new Date().toISOString();

// Colon in filenames is not supported in Windows, so we must replace them
if (process.platform === 'win32') {
  now = now.replace(/:/gi, '.');
}

/**
 *  Definition of all of the different arguments that can be passed to the
 * license checker utility via CLI.
 */
module.exports = yargs
  .option('failOn', {
    description: 'fail (exit with code 1) on the first occurrence of the licenses of the comma-separated list',
    type: 'string',
  })
  .option('generateOutputOn', {
    description: 'generates an output file only if any the licenses of the comma-separated list exist (output generated by default).',
    type: 'string',
  })
  .option('outputFileName', {
    description: 'name of the output file generated',
    type: 'string',
    default: `licence-report-${now}`
  })
  .option('errorReportFileName', {
    description: 'name of the file generated when a licence in the failOn option is found',
    type: 'string',
    default: `license-error-${now}`
  })
  .option('disableErrorReport', {
    description: 'flag to disable the error report file generation',
    type: 'boolean',
    default: false
  })
  .help()
  .alias('help', 'h')
  .argv;