const yargs = require('yargs');

let timestamp = new Date().toISOString();

// Colon in filenames is not supported in Windows, so we must replace them
if (process.platform === 'win32') {
  timestamp = timestamp.replace(/:/gi, '.');
}

/**
 *  Definition of all of the different arguments that can be passed to the
 * license checker utility via CLI.
 */
module.exports = yargs
  .option('start', {
    description: 'path of the initial json to look for',
    type: 'string',
    default: process.cwd(),
  })
  .option('failOn', {
    description: 'fail (exit with code 1) on the first occurrence of the licenses of the comma-separated list',
    type: 'string',
  })
  .option('generateOutputOn', {
    description: 'generates an output file only if any the licenses of the comma-separated list exist (output generated by default).',
    type: 'string',
  })
  .option('outputFileName', {
    description: 'name of the output file generated',
    type: 'string',
    default: `licence-report-${timestamp}`
  })
  .option('errorReportFileName', {
    description: 'name of the file generated when a licence in the failOn option is found',
    type: 'string',
    default: `license-error-${timestamp}`
  })
  .option('disableErrorReport', {
    description: 'flag to disable the error report file generation',
    type: 'boolean',
    default: false
  })
  .option('disableReport', {
    description: 'flag to disable the report file generation, whether there is an error or not',
    type: 'boolean',
    default: false
  })
  .help()
  .alias('help', 'h')
  .argv;
